use crate::engine::CopyResult;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

pub fn write_hashfile(
    source_root: &Path,
    results: &[CopyResult],
    dest_root: &Path,
) -> PathBuf {
    let stem = if source_root.is_file() {
        source_root
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string()
    } else {
        source_root
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string()
    };

    let hashfile_path = dest_root.join(format!("{stem}.xxh3"));

    let mut f = fs::File::create(&hashfile_path).expect("failed to create hash file");
    writeln!(f, "; xxHash3-64 checksums generated by cvv").unwrap();
    writeln!(f, ";").unwrap();
    writeln!(f).unwrap();

    for result in results {
        if !result.success || result.inflight_hash.is_empty() {
            continue;
        }
        let rel = result.relative_path.to_string_lossy().replace('\\', "/");
        writeln!(f, "{} *{}", result.inflight_hash, rel).unwrap();
    }

    hashfile_path
}
