use crate::engine::CopyResult;
use std::collections::HashMap;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

// Parses an existing hashfile ("HASH *relative/path" lines, ';' comments, blank lines)
// into a path->hash map so hashes for collision-skipped files can be recovered.
fn parse_hashfile(path: &Path) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let Ok(content) = fs::read_to_string(path) else {
        return map;
    };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(';') {
            continue;
        }
        if let Some((hash, rest)) = line.split_once(' ') {
            if let Some(rel) = rest.strip_prefix('*') {
                map.insert(rel.to_string(), hash.to_string());
            }
        }
    }
    map
}

pub fn write_hashfile(
    source_root: &Path,
    results: &[CopyResult],
    dest_root: &Path,
) -> io::Result<PathBuf> {
    let stem = if source_root.is_file() {
        source_root
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string()
    } else {
        source_root
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string()
    };

    let hashfile_path = dest_root.join(format!("{stem}.xxh3"));
    let existing = parse_hashfile(&hashfile_path);

    let mut f = fs::File::create(&hashfile_path)?;
    writeln!(f, "; xxHash3-64 checksums generated by cvv")?;
    writeln!(f, ";")?;
    writeln!(f)?;

    let mut missing = 0;
    for result in results {
        if !result.success {
            continue;
        }
        let rel = result.relative_path.to_string_lossy().replace('\\', "/");
        let hash = if !result.inflight_hash.is_empty() {
            Some(result.inflight_hash.clone())
        } else {
            existing.get(&rel).cloned()
        };
        match hash {
            Some(h) => writeln!(f, "{h} *{rel}")?,
            None => missing += 1,
        }
    }

    if missing > 0 {
        eprintln!(
            "Warning: {missing} file(s) missing from hashfile (no hash available): rerun with source or target verification to complete it"
        );
    }

    Ok(hashfile_path)
}
